const SUBMIT_EMAIL = 'SUBMIT_EMAIL';
const SUBMIT_EXPENSE = 'SUBMIT_EXPENSE';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const EDITOR_ON = 'EDITOR_ON';

export { SUBMIT_EMAIL, SUBMIT_EXPENSE };
